# Stage 1: Development stage
FROM --platform=linux/amd64 node:22-alpine AS development

# Set environment to development
ENV NODE_ENV development

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the development port (React app usually runs on 3000)
EXPOSE 3000

# Start the React app in development mode
CMD [ "npm", "start" ]